// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqbI6otNC1P-_VPy7AoKerdxuXmV5ILbY',
    appId: '1:666827595467:web:d9493923ad08e031c5854e',
    messagingSenderId: '666827595467',
    projectId: 'baeber-app',
    authDomain: 'baeber-app.firebaseapp.com',
    storageBucket: 'baeber-app.appspot.com',
    measurementId: 'G-875LKSHTT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUUzngHnx8w8jwpxrwAKqh-t8sHld0mdY',
    appId: '1:666827595467:android:89b60d29b929fc98c5854e',
    messagingSenderId: '666827595467',
    projectId: 'baeber-app',
    storageBucket: 'baeber-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt-2-3oXesMk0ukGzMbnXZifG56POce_k',
    appId: '1:666827595467:ios:a8bf17689385b17dc5854e',
    messagingSenderId: '666827595467',
    projectId: 'baeber-app',
    storageBucket: 'baeber-app.appspot.com',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt-2-3oXesMk0ukGzMbnXZifG56POce_k',
    appId: '1:666827595467:ios:602dd51b4a36779cc5854e',
    messagingSenderId: '666827595467',
    projectId: 'baeber-app',
    storageBucket: 'baeber-app.appspot.com',
    iosBundleId: 'com.example.barber.RunnerTests',
  );
}
